[package]
name = "rust_extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
strip = true

[dependencies]
wai-bindgen-rust = "0.2.3"
wee_alloc = "0.4.5"
